spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zeroorder?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    username: root
    password: 1
  #    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
  #    driver-class-name: org.h2.Driver
  #    username: sa
  #    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  redis:
    host: localhost
    port: 6379

server:
  port: 8082